import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/Product.js";
import DietPlan from "./models/DietPlan.js";
import Recipe from "./models/Recipe.js";
import Partnership from "./models/Partnership.js";

dotenv.config();

const seedData = {
  recipes: [
    {
      name: "Quinoa Buddha Bowl",
      description:
        "A delicious and nutritious meal perfect for your diet plan.",
      difficulty: "Easy",
      cookingTime: "25 minutes",
      servings: 2,
      calories: 420,
      image: "🥗",
      tags: ["Vegan", "High Protein", "Budget Friendly"],
      ingredients: [
        {
          name: "Quinoa",
          productName: "Quinoa",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Sweet potato",
          productName: "Sweet potato",
          quantity: "1 medium",
          inPantry: false,
        },
        {
          name: "Chickpeas",
          productName: "Chickpeas",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Kale",
          productName: "Kale",
          quantity: "2 cups",
          inPantry: false,
        },
        {
          name: "Avocado",
          productName: "Avocado",
          quantity: "1",
          inPantry: false,
        },
      ],
      instructions: [
        "Cook quinoa according to package instructions",
        "Roast sweet potato until tender",
        "Drain and rinse chickpeas",
        "Massage kale with olive oil",
        "Arrange all ingredients in a bowl and enjoy!",
      ],
      nutrition: {
        calories: 420,
        protein: "15g",
        fat: "18g",
        carbs: "45g",
        fiber: "12g",
      },
      dietCompatible: ["vegan", "vegetarian", "gluten-free"],
      author: "Chef Sarah",
      rating: 4.8,
      reviews: 127,
      subscriptionTier: "free",
    },
    {
      name: "Mediterranean Salmon",
      description:
        "A delicious and nutritious meal perfect for your diet plan.",
      difficulty: "Medium",
      cookingTime: "35 minutes",
      servings: 2,
      calories: 580,
      image: "🐟",
      tags: ["High Protein", "Omega-3", "Premium"],
      ingredients: [
        {
          name: "Salmon fillet",
          productName: "Salmon fillet",
          quantity: "2 pieces",
          inPantry: false,
        },
        {
          name: "Olive oil",
          productName: "Olive oil",
          quantity: "2 tbsp",
          inPantry: false,
        },
        {
          name: "Lemon",
          productName: "Lemon",
          quantity: "1",
          inPantry: false,
        },
        {
          name: "Fresh herbs",
          productName: "Fresh herbs",
          quantity: "1/4 cup",
          inPantry: false,
        },
        {
          name: "Quinoa",
          productName: "Quinoa",
          quantity: "1 cup",
          inPantry: false,
        },
      ],
      instructions: [
        "Season salmon with herbs and lemon",
        "Heat olive oil in a pan",
        "Cook salmon until flaky",
        "Cook quinoa as a side",
        "Serve with fresh herbs and lemon wedges",
      ],
      nutrition: {
        calories: 580,
        protein: "45g",
        fat: "32g",
        carbs: "28g",
        fiber: "4g",
      },
      dietCompatible: ["keto", "paleo", "mediterranean"],
      author: "Chef Maria",
      rating: 4.6,
      reviews: 89,
      subscriptionTier: "free",
    },
    // FREE TIER RECIPES
    {
      name: "Overnight Oats with Berries",
      description:
        "Healthy and delicious overnight oats perfect for busy mornings",
      difficulty: "Easy",
      cookingTime: "5 minutes + overnight",
      servings: 1,
      calories: 320,
      image: "🥣",
      tags: ["Vegan", "High Fiber", "Budget Friendly"],
      ingredients: [
        {
          name: "Oats",
          productName: "Oats",
          quantity: "1/2 cup",
          inPantry: false,
        },
        {
          name: "Almond milk",
          productName: "Almond milk",
          quantity: "1/2 cup",
          inPantry: false,
        },
        {
          name: "Chia seeds",
          productName: "Chia seeds",
          quantity: "1 tbsp",
          inPantry: false,
        },
        {
          name: "Honey",
          productName: "Honey",
          quantity: "1 tsp",
          inPantry: false,
        },
        {
          name: "Mixed berries",
          productName: "Mixed berries",
          quantity: "1/4 cup",
          inPantry: false,
        },
      ],
      instructions: [
        "Mix oats, almond milk, and chia seeds in a jar",
        "Add honey and stir well",
        "Refrigerate overnight",
        "Top with fresh berries before serving",
      ],
      nutrition: {
        calories: 320,
        protein: "8g",
        fat: "12g",
        carbs: "45g",
        fiber: "8g",
      },
      dietCompatible: ["vegan", "vegetarian", "gluten-free"],
      author: "Chef Sarah",
      rating: 4.5,
      reviews: 89,
      subscriptionTier: "free",
    },
    {
      name: "Greek Yogurt Parfait",
      description: "Protein-rich parfait with fresh fruits and granola",
      difficulty: "Easy",
      cookingTime: "10 minutes",
      servings: 1,
      calories: 280,
      image: "🥛",
      tags: ["High Protein", "Quick", "Healthy"],
      ingredients: [
        {
          name: "Greek yogurt",
          productName: "Greek yogurt",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Honey",
          productName: "Honey",
          quantity: "1 tbsp",
          inPantry: false,
        },
        {
          name: "Granola",
          productName: "Granola",
          quantity: "1/4 cup",
          inPantry: false,
        },
        {
          name: "Mixed berries",
          productName: "Mixed berries",
          quantity: "1/2 cup",
          inPantry: false,
        },
      ],
      instructions: [
        "Layer Greek yogurt in a glass",
        "Drizzle with honey",
        "Add granola layer",
        "Top with fresh berries",
      ],
      nutrition: {
        calories: 280,
        protein: "20g",
        fat: "8g",
        carbs: "35g",
        fiber: "4g",
      },
      dietCompatible: ["vegetarian"],
      author: "Chef Maria",
      rating: 4.7,
      reviews: 156,
      subscriptionTier: "free",
    },

    // PREMIUM TIER RECIPES
    {
      name: "Protein Power Bowl",
      description: "High-protein bowl with quinoa, chicken, and vegetables",
      difficulty: "Medium",
      cookingTime: "25 minutes",
      servings: 2,
      calories: 450,
      image: "🍗",
      tags: ["High Protein", "Muscle Building", "Premium"],
      ingredients: [
        {
          name: "Chicken breast",
          productName: "Chicken breast",
          quantity: "200g",
          inPantry: false,
        },
        {
          name: "Quinoa",
          productName: "Quinoa",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Broccoli",
          productName: "Broccoli",
          quantity: "2 cups",
          inPantry: false,
        },
        {
          name: "Cherry tomatoes",
          productName: "Cherry tomatoes",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Olive oil",
          productName: "Olive oil",
          quantity: "2 tbsp",
          inPantry: false,
        },
      ],
      instructions: [
        "Cook quinoa according to package instructions",
        "Season and grill chicken breast",
        "Steam broccoli until tender",
        "Assemble bowl with quinoa, chicken, and vegetables",
        "Drizzle with olive oil and seasonings",
      ],
      nutrition: {
        calories: 450,
        protein: "35g",
        fat: "18g",
        carbs: "35g",
        fiber: "8g",
      },
      dietCompatible: ["keto", "paleo", "mediterranean"],
      author: "Coach Mike",
      rating: 4.8,
      reviews: 234,
      subscriptionTier: "premium",
    },
    {
      name: "Keto Fat Bombs",
      description: "Delicious high-fat snacks perfect for ketogenic diet",
      difficulty: "Easy",
      cookingTime: "15 minutes",
      servings: 12,
      calories: 120,
      image: "💣",
      tags: ["Keto", "High Fat", "Quick"],
      ingredients: [
        {
          name: "Coconut oil",
          productName: "Coconut oil",
          quantity: "1/2 cup",
          inPantry: false,
        },
        {
          name: "Cocoa powder",
          productName: "Cocoa powder",
          quantity: "1/4 cup",
          inPantry: false,
        },
        {
          name: "Almonds",
          productName: "Almonds",
          quantity: "1/4 cup",
          inPantry: false,
        },
        {
          name: "Honey",
          productName: "Honey",
          quantity: "2 tbsp",
          inPantry: false,
        },
      ],
      instructions: [
        "Melt coconut oil in a saucepan",
        "Mix in cocoa powder and honey",
        "Pour into silicone molds",
        "Sprinkle with chopped almonds",
        "Freeze until solid",
      ],
      nutrition: {
        calories: 120,
        protein: "2g",
        fat: "12g",
        carbs: "4g",
        fiber: "2g",
      },
      dietCompatible: ["keto", "paleo"],
      author: "Dr. Sarah Wilson",
      rating: 4.9,
      reviews: 189,
      subscriptionTier: "premium",
    },

    // PRO TIER RECIPES
    {
      name: "Elite Recovery Smoothie",
      description:
        "Advanced recovery smoothie for elite athletes and performance",
      difficulty: "Easy",
      cookingTime: "10 minutes",
      servings: 1,
      calories: 380,
      image: "🥤",
      tags: ["Recovery", "High Protein", "Elite"],
      ingredients: [
        {
          name: "Protein powder",
          productName: "Protein powder",
          quantity: "30g",
          inPantry: false,
        },
        {
          name: "Banana",
          productName: "Banana",
          quantity: "1 medium",
          inPantry: false,
        },
        {
          name: "Greek yogurt",
          productName: "Greek yogurt",
          quantity: "1/2 cup",
          inPantry: false,
        },
        {
          name: "Almond milk",
          productName: "Almond milk",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Chia seeds",
          productName: "Chia seeds",
          quantity: "1 tbsp",
          inPantry: false,
        },
      ],
      instructions: [
        "Add all ingredients to a blender",
        "Blend until smooth and creamy",
        "Serve immediately for best results",
      ],
      nutrition: {
        calories: 380,
        protein: "35g",
        fat: "8g",
        carbs: "35g",
        fiber: "6g",
      },
      dietCompatible: ["vegetarian"],
      author: "Elite Coach",
      rating: 4.9,
      reviews: 89,
      subscriptionTier: "pro",
    },
    {
      name: "Medical-Grade Bone Broth",
      description: "Therapeutic bone broth for healing and recovery",
      difficulty: "Hard",
      cookingTime: "24 hours",
      servings: 8,
      calories: 45,
      image: "🍲",
      tags: ["Healing", "Therapeutic", "Medical"],
      ingredients: [
        {
          name: "Beef bones",
          productName: "Beef bones",
          quantity: "2kg",
          inPantry: false,
        },
        {
          name: "Onion",
          productName: "Onion",
          quantity: "2 medium",
          inPantry: false,
        },
        {
          name: "Carrots",
          productName: "Carrots",
          quantity: "4 medium",
          inPantry: false,
        },
        {
          name: "Garlic",
          productName: "Garlic",
          quantity: "8 cloves",
          inPantry: false,
        },
        {
          name: "Apple cider vinegar",
          productName: "Apple cider vinegar",
          quantity: "2 tbsp",
          inPantry: false,
        },
      ],
      instructions: [
        "Roast bones in oven at 400°F for 30 minutes",
        "Add bones and vegetables to large pot",
        "Cover with water and add vinegar",
        "Simmer for 24 hours on low heat",
        "Strain and store in refrigerator",
      ],
      nutrition: {
        calories: 45,
        protein: "8g",
        fat: "2g",
        carbs: "2g",
        fiber: "1g",
      },
      dietCompatible: ["keto", "paleo", "mediterranean"],
      author: "Dr. Nutrition Expert",
      rating: 4.8,
      reviews: 67,
      subscriptionTier: "pro",
    },
  ],

  dietPlans: [
    // FREE TIER DIET PLANS
    {
      name: "Keto Basics",
      description:
        "High fat, low carb diet for rapid weight loss and improved metabolism",
      benefits: [
        "Rapid weight loss",
        "Increased energy",
        "Mental clarity",
        "Stable blood sugar",
      ],
      difficulty: "Medium",
      duration: "30 days",
      color: "from-purple-500 to-pink-500",
      icon: "🥑",
      price: 0,
      features: ["Basic meal plans", "Grocery lists", "Community support"],
      sampleMeals: ["Avocado & Eggs", "Salmon with Greens", "Keto Smoothie"],
      restrictions: ["Low carb", "High fat", "Moderate protein"],
      suitableFor: ["Weight loss", "Diabetes management", "Energy boost"],
      weeklyMeals: [],
      groceryList: [
        "Avocados",
        "Salmon",
        "Chicken breast",
        "Eggs",
        "Coconut oil",
        "Almonds",
      ],
      nutritionInfo: {
        calories: 1800,
        protein: 120,
        carbs: 20,
        fat: 140,
        fiber: 25,
      },
      subscriptionTier: "free",
    },
    {
      name: "Mediterranean Essentials",
      description:
        "Heart-healthy diet rich in healthy fats, whole grains, and fresh produce",
      benefits: [
        "Heart health",
        "Longevity",
        "Brain function",
        "Reduced inflammation",
      ],
      difficulty: "Easy",
      duration: "60 days",
      color: "from-blue-500 to-cyan-500",
      icon: "🫒",
      price: 0,
      features: [
        "Balanced nutrition",
        "Fresh ingredients",
        "Flexible meal planning",
      ],
      sampleMeals: ["Greek Salad", "Grilled Fish", "Hummus & Pita"],
      restrictions: [
        "Moderate portions",
        "Limited red meat",
        "Low processed foods",
      ],
      suitableFor: ["Heart health", "Weight maintenance", "General wellness"],
      weeklyMeals: [],
      groceryList: [
        "Olive oil",
        "Fish and seafood",
        "Fresh vegetables",
        "Whole grains",
        "Nuts and seeds",
        "Herbs and spices",
      ],
      nutritionInfo: {
        calories: 2000,
        protein: 100,
        carbs: 200,
        fat: 70,
        fiber: 30,
      },
      subscriptionTier: "free",
    },
    {
      name: "Vegan Starter",
      description: "Plant-based nutrition for ethical and health benefits",
      benefits: [
        "Lower cholesterol",
        "Reduced cancer risk",
        "Environmental impact",
        "Ethical choice",
      ],
      difficulty: "Medium",
      duration: "45 days",
      color: "from-green-500 to-emerald-500",
      icon: "🌱",
      price: 0,
      features: ["Plant-based recipes", "Nutrition guidance", "Meal prep tips"],
      sampleMeals: ["Tofu Scramble", "Lentil Curry", "Vegan Buddha Bowl"],
      restrictions: ["No animal products", "No dairy", "No eggs"],
      suitableFor: [
        "Ethical eating",
        "Health improvement",
        "Environmental consciousness",
      ],
      weeklyMeals: [],
      groceryList: [
        "Tofu and tempeh",
        "Legumes",
        "Fresh vegetables",
        "Whole grains",
        "Nuts and seeds",
        "Plant milk",
      ],
      nutritionInfo: {
        calories: 1800,
        protein: 80,
        carbs: 250,
        fat: 60,
        fiber: 35,
      },
      subscriptionTier: "free",
    },

    // PREMIUM TIER DIET PLANS
    {
      name: "High-Protein Muscle Builder",
      description:
        "Optimized nutrition for muscle growth and athletic performance",
      benefits: [
        "Muscle growth",
        "Improved strength",
        "Better recovery",
        "Enhanced performance",
      ],
      difficulty: "Medium",
      duration: "90 days",
      color: "from-orange-500 to-red-500",
      icon: "💪",
      price: 499,
      features: [
        "Advanced meal plans",
        "Progress tracking",
        "Personalized macros",
        "Expert guidance",
      ],
      sampleMeals: [
        "Protein Smoothie",
        "Grilled Chicken Bowl",
        "Lean Beef with Sweet Potato",
      ],
      restrictions: ["High protein", "Moderate carbs", "Timed nutrition"],
      suitableFor: [
        "Muscle building",
        "Athletic performance",
        "Strength training",
      ],
      weeklyMeals: [],
      groceryList: [
        "Chicken breast",
        "Lean beef",
        "Fish",
        "Eggs",
        "Greek yogurt",
        "Protein powder",
        "Quinoa",
        "Sweet potatoes",
      ],
      nutritionInfo: {
        calories: 2500,
        protein: 180,
        carbs: 200,
        fat: 80,
        fiber: 35,
      },
      subscriptionTier: "premium",
    },
    {
      name: "DASH Heart Health",
      description:
        "Dietary Approaches to Stop Hypertension - clinically proven heart-healthy eating",
      benefits: [
        "Lower blood pressure",
        "Heart health",
        "Reduced stroke risk",
        "Better cholesterol",
      ],
      difficulty: "Easy",
      duration: "60 days",
      color: "from-red-500 to-pink-500",
      icon: "❤️",
      price: 499,
      features: [
        "Medical-grade plans",
        "Blood pressure tracking",
        "Heart health monitoring",
        "Expert consultation",
      ],
      sampleMeals: [
        "Oatmeal with Berries",
        "Grilled Chicken Salad",
        "Baked Fish with Vegetables",
      ],
      restrictions: ["Low sodium", "Heart-healthy fats", "High fiber"],
      suitableFor: ["Heart health", "Hypertension", "Cholesterol management"],
      weeklyMeals: [],
      groceryList: [
        "Oatmeal",
        "Fresh fruits",
        "Vegetables",
        "Lean proteins",
        "Low-fat dairy",
        "Nuts and seeds",
      ],
      nutritionInfo: {
        calories: 1800,
        protein: 100,
        carbs: 250,
        fat: 60,
        fiber: 40,
      },
      subscriptionTier: "premium",
    },
    {
      name: "Weight Loss Pro",
      description:
        "Advanced weight loss program with personalized coaching and tracking",
      benefits: [
        "Sustainable weight loss",
        "Metabolic boost",
        "Improved body composition",
        "Long-term success",
      ],
      difficulty: "Medium",
      duration: "120 days",
      color: "from-blue-500 to-purple-500",
      icon: "📉",
      price: 499,
      features: [
        "Personalized coaching",
        "Progress tracking",
        "Metabolic testing",
        "Community support",
      ],
      sampleMeals: [
        "Green Smoothie Bowl",
        "Lean Protein Salad",
        "Light Dinner Options",
      ],
      restrictions: ["Calorie deficit", "High protein", "Low processed foods"],
      suitableFor: ["Weight loss", "Body composition", "Metabolic health"],
      weeklyMeals: [],
      groceryList: [
        "Lean proteins",
        "Fresh vegetables",
        "Complex carbs",
        "Healthy fats",
        "Protein supplements",
      ],
      nutritionInfo: {
        calories: 1500,
        protein: 120,
        carbs: 150,
        fat: 50,
        fiber: 30,
      },
      subscriptionTier: "premium",
    },

    // PRO TIER DIET PLANS
    {
      name: "Intermittent Fasting Elite",
      description:
        "Advanced intermittent fasting protocol with personalized coaching and monitoring",
      benefits: [
        "Rapid fat loss",
        "Autophagy benefits",
        "Improved insulin sensitivity",
        "Enhanced longevity",
      ],
      difficulty: "Hard",
      duration: "90 days",
      color: "from-purple-500 to-indigo-500",
      icon: "⏰",
      price: 799,
      features: [
        "1-on-1 coaching",
        "Advanced tracking",
        "Biometric monitoring",
        "Custom protocols",
      ],
      sampleMeals: [
        "Fasting protocols",
        "High-protein meals",
        "Nutrient timing",
      ],
      restrictions: [
        "Fasting windows",
        "Specific meal timing",
        "Strict protocols",
      ],
      suitableFor: [
        "Advanced fasting",
        "Fat loss",
        "Longevity",
        "Metabolic health",
      ],
      weeklyMeals: [],
      groceryList: [
        "High-quality proteins",
        "Healthy fats",
        "Low-carb vegetables",
        "Supplements",
        "Electrolytes",
      ],
      nutritionInfo: {
        calories: 1800,
        protein: 150,
        carbs: 100,
        fat: 100,
        fiber: 25,
      },
      subscriptionTier: "pro",
    },
    {
      name: "Athletic Performance Elite",
      description:
        "Elite nutrition program for professional athletes and high-performance individuals",
      benefits: [
        "Peak performance",
        "Optimal recovery",
        "Enhanced endurance",
        "Competitive edge",
      ],
      difficulty: "Expert",
      duration: "180 days",
      color: "from-yellow-500 to-orange-500",
      icon: "🏆",
      price: 799,
      features: [
        "Elite coaching",
        "Performance analytics",
        "Recovery optimization",
        "Competition prep",
      ],
      sampleMeals: [
        "Performance meals",
        "Recovery shakes",
        "Competition nutrition",
      ],
      restrictions: [
        "Performance-focused",
        "Timed nutrition",
        "Supplement protocols",
      ],
      suitableFor: [
        "Professional athletes",
        "Elite performance",
        "Competition prep",
      ],
      weeklyMeals: [],
      groceryList: [
        "Premium proteins",
        "Performance supplements",
        "Recovery products",
        "Elite nutrition",
      ],
      nutritionInfo: {
        calories: 3000,
        protein: 200,
        carbs: 300,
        fat: 100,
        fiber: 40,
      },
      subscriptionTier: "pro",
    },
    {
      name: "Medical Nutrition Therapy",
      description:
        "Specialized nutrition plans for medical conditions with expert supervision",
      benefits: [
        "Medical-grade nutrition",
        "Condition management",
        "Expert supervision",
        "Health monitoring",
      ],
      difficulty: "Expert",
      duration: "365 days",
      color: "from-green-500 to-blue-500",
      icon: "🏥",
      price: 799,
      features: [
        "Medical supervision",
        "Condition-specific plans",
        "Regular monitoring",
        "Expert consultation",
      ],
      sampleMeals: [
        "Medical-grade meals",
        "Condition-specific nutrition",
        "Therapeutic foods",
      ],
      restrictions: [
        "Medical protocols",
        "Specific guidelines",
        "Regular monitoring",
      ],
      suitableFor: [
        "Medical conditions",
        "Therapeutic nutrition",
        "Health management",
      ],
      weeklyMeals: [],
      groceryList: [
        "Medical-grade foods",
        "Supplements",
        "Therapeutic ingredients",
      ],
      nutritionInfo: {
        calories: 2000,
        protein: 120,
        carbs: 200,
        fat: 70,
        fiber: 30,
      },
      subscriptionTier: "pro",
    },
  ],

  products: [
    {
      name: "Quinoa",
      description: "Premium organic quinoa rich in protein and fiber",
      price: 120,
      originalPrice: 150,
      category: "Grains",
      dietCompatible: ["vegan", "vegetarian", "gluten-free", "keto", "paleo"],
      image: "🌾",
      inStock: true,
      stockQuantity: 50,
      unit: "1kg",
      rating: 4.8,
      reviews: 124,
      supplier: "Fresh Valley Farms",
      tags: ["Organic", "Premium", "Local"],
    },
    {
      name: "Sweet potato",
      description: "Fresh organic sweet potatoes, rich in vitamins and fiber",
      price: 40,
      originalPrice: 50,
      category: "Vegetables",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🍠",
      inStock: true,
      stockQuantity: 100,
      unit: "500g",
      rating: 4.7,
      reviews: 156,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Chickpeas",
      description: "Organic chickpeas, excellent source of plant protein",
      price: 60,
      originalPrice: 75,
      category: "Legumes",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🫘",
      inStock: true,
      stockQuantity: 80,
      unit: "400g can",
      rating: 4.6,
      reviews: 89,
      tags: ["Organic", "Canned", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Kale",
      description: "Fresh organic kale, nutrient-dense leafy green",
      price: 30,
      originalPrice: 40,
      category: "Vegetables",
      dietCompatible: ["vegan", "vegetarian", "keto", "paleo", "mediterranean"],
      image: "🥬",
      inStock: true,
      stockQuantity: 60,
      unit: "1 bunch",
      rating: 4.5,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Avocado",
      description: "Fresh organic avocados, perfect for healthy fats",
      price: 80,
      originalPrice: 100,
      category: "Fruits",
      dietCompatible: ["vegan", "vegetarian", "keto", "paleo", "mediterranean"],
      image: "🥑",
      inStock: true,
      stockQuantity: 100,
      unit: "1 piece",
      rating: 4.7,
      reviews: 156,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Salmon fillet",
      description: "Wild-caught Atlantic salmon, rich in omega-3 fatty acids",
      price: 400,
      originalPrice: 500,
      category: "Seafood",
      dietCompatible: ["keto", "paleo", "mediterranean", "dash"],
      image: "🐟",
      inStock: true,
      stockQuantity: 25,
      unit: "300g",
      rating: 4.9,
      reviews: 89,
      tags: ["Wild-caught", "Fresh", "Premium"],
      supplier: "Coastal Fish Market",
    },
    {
      name: "Olive oil",
      description: "Extra virgin olive oil, heart-healthy cooking oil",
      price: 200,
      originalPrice: 250,
      category: "Oils",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🫒",
      inStock: true,
      stockQuantity: 40,
      unit: "500ml",
      rating: 4.8,
      reviews: 234,
      tags: ["Extra Virgin", "Premium", "Imported"],
      supplier: "Mediterranean Imports",
    },
    {
      name: "Lemon",
      description: "Fresh organic lemons, perfect for cooking and beverages",
      price: 20,
      originalPrice: 25,
      category: "Fruits",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍋",
      inStock: true,
      stockQuantity: 150,
      unit: "1 piece",
      rating: 4.6,
      reviews: 89,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Fresh herbs",
      description: "Assorted fresh herbs for cooking and garnishing",
      price: 50,
      originalPrice: 60,
      category: "Herbs",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🌿",
      inStock: true,
      stockQuantity: 30,
      unit: "1 bunch",
      rating: 4.7,
      reviews: 45,
      tags: ["Fresh", "Local", "Organic"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Tomato",
      description: "Fresh organic tomatoes, perfect for salads and cooking",
      price: 25,
      originalPrice: 30,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍅",
      inStock: true,
      stockQuantity: 120,
      unit: "500g",
      rating: 4.6,
      reviews: 78,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Onion",
      description: "Fresh organic onions, essential cooking ingredient",
      price: 30,
      originalPrice: 35,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🧅",
      inStock: true,
      stockQuantity: 200,
      unit: "1kg",
      rating: 4.5,
      reviews: 56,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Garlic",
      description: "Fresh organic garlic, essential for flavoring dishes",
      price: 40,
      originalPrice: 50,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🧄",
      inStock: true,
      stockQuantity: 80,
      unit: "200g",
      rating: 4.7,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Organic Quinoa",
      description: "Premium organic quinoa rich in protein and fiber",
      price: 299,
      originalPrice: 399,
      category: "Grains",
      dietCompatible: ["vegan", "vegetarian", "gluten-free", "keto", "paleo"],
      image: "🌾",
      inStock: true,
      stockQuantity: 50,
      unit: "500g",
      rating: 4.8,
      reviews: 124,
      supplier: "Fresh Valley Farms",
      tags: ["Organic", "Premium", "Local"],
    },
    {
      name: "Greek Yogurt",
      description: "Creamy Greek yogurt high in protein and probiotics",
      price: 149,
      originalPrice: 199,
      category: "Dairy",
      dietCompatible: ["vegetarian", "mediterranean", "dash"],
      image: "🥛",
      inStock: true,
      stockQuantity: 75,
      unit: "500g",
      rating: 4.6,
      reviews: 203,
      tags: ["Fresh", "Local", "Premium"],
      supplier: "Mountain Dairy Co.",
    },
    {
      name: "Almonds",
      description: "Premium raw almonds, excellent source of healthy fats",
      price: 399,
      originalPrice: 499,
      category: "Nuts",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥜",
      inStock: true,
      stockQuantity: 60,
      unit: "500g",
      rating: 4.8,
      reviews: 178,
      tags: ["Raw", "Premium", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Cucumber",
      description: "Fresh organic cucumbers, perfect for salads",
      price: 35,
      originalPrice: 45,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥒",
      inStock: true,
      stockQuantity: 90,
      unit: "500g",
      rating: 4.5,
      reviews: 45,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Cherry Tomatoes",
      description: "Sweet cherry tomatoes, perfect for salads and cooking",
      price: 45,
      originalPrice: 55,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍅",
      inStock: true,
      stockQuantity: 70,
      unit: "250g",
      rating: 4.6,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Salt",
      description: "Fine sea salt for cooking and seasoning",
      price: 25,
      originalPrice: 30,
      category: "Seasonings",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🧂",
      inStock: true,
      stockQuantity: 100,
      unit: "200g",
      rating: 4.5,
      reviews: 45,
      tags: ["Sea Salt", "Fine", "Essential"],
      supplier: "Spice Market",
    },
    {
      name: "Bread",
      description: "Fresh whole grain bread, perfect for toasting",
      price: 35,
      originalPrice: 40,
      category: "Bakery",
      dietCompatible: ["vegetarian"],
      image: "🍞",
      inStock: true,
      stockQuantity: 50,
      unit: "1 loaf",
      rating: 4.4,
      reviews: 89,
      tags: ["Fresh", "Whole Grain", "Local"],
      supplier: "Local Bakery",
    },
    {
      name: "Honey",
      description: "Pure natural honey, perfect for sweetening",
      price: 120,
      originalPrice: 150,
      category: "Sweeteners",
      dietCompatible: ["vegan", "vegetarian", "mediterranean"],
      image: "🍯",
      inStock: true,
      stockQuantity: 40,
      unit: "500g",
      rating: 4.7,
      reviews: 156,
      tags: ["Natural", "Pure", "Local"],
      supplier: "Honey Farm",
    },
    {
      name: "Oats",
      description: "Whole grain oats, perfect for breakfast and baking",
      price: 45,
      originalPrice: 55,
      category: "Grains",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🌾",
      inStock: true,
      stockQuantity: 80,
      unit: "500g",
      rating: 4.6,
      reviews: 78,
      tags: ["Whole Grain", "Healthy", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Almond milk",
      description: "Plant-based almond milk, dairy-free alternative",
      price: 120,
      originalPrice: 150,
      category: "Beverages",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥛",
      inStock: true,
      stockQuantity: 60,
      unit: "1L",
      rating: 4.5,
      reviews: 134,
      tags: ["Plant-based", "Dairy-free", "Healthy"],
      supplier: "Plant Milk Co.",
    },
    {
      name: "Chia seeds",
      description: "Nutrient-rich chia seeds, excellent source of omega-3",
      price: 180,
      originalPrice: 220,
      category: "Seeds",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🌱",
      inStock: true,
      stockQuantity: 40,
      unit: "250g",
      rating: 4.7,
      reviews: 89,
      tags: ["Superfood", "Omega-3", "Premium"],
      supplier: "Superfood Market",
    },
    {
      name: "Mixed berries",
      description: "Fresh mixed berries, perfect for smoothies and desserts",
      price: 150,
      originalPrice: 180,
      category: "Fruits",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🫐",
      inStock: true,
      stockQuantity: 50,
      unit: "300g",
      rating: 4.6,
      reviews: 67,
      tags: ["Fresh", "Antioxidant", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Granola",
      description: "Homemade granola with nuts and dried fruits",
      price: 200,
      originalPrice: 250,
      category: "Breakfast",
      dietCompatible: ["vegetarian", "mediterranean"],
      image: "🥣",
      inStock: true,
      stockQuantity: 30,
      unit: "400g",
      rating: 4.5,
      reviews: 45,
      tags: ["Homemade", "Healthy", "Local"],
      supplier: "Local Bakery",
    },
    {
      name: "Chicken breast",
      description: "Lean chicken breast, excellent source of protein",
      price: 300,
      originalPrice: 350,
      category: "Meat",
      dietCompatible: ["keto", "paleo", "mediterranean", "dash"],
      image: "🍗",
      inStock: true,
      stockQuantity: 45,
      unit: "500g",
      rating: 4.8,
      reviews: 234,
      tags: ["Lean", "High Protein", "Fresh"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Broccoli",
      description: "Fresh organic broccoli, rich in vitamins and minerals",
      price: 60,
      originalPrice: 75,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥦",
      inStock: true,
      stockQuantity: 70,
      unit: "500g",
      rating: 4.6,
      reviews: 89,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Coconut oil",
      description: "Pure coconut oil, perfect for cooking and baking",
      price: 250,
      originalPrice: 300,
      category: "Oils",
      dietCompatible: ["vegan", "vegetarian", "keto", "paleo", "mediterranean"],
      image: "🥥",
      inStock: true,
      stockQuantity: 35,
      unit: "500ml",
      rating: 4.7,
      reviews: 156,
      tags: ["Pure", "Organic", "Premium"],
      supplier: "Coconut Paradise",
    },
    {
      name: "Cocoa powder",
      description: "Pure cocoa powder, perfect for baking and beverages",
      price: 180,
      originalPrice: 220,
      category: "Baking",
      dietCompatible: ["vegan", "vegetarian", "keto", "paleo", "mediterranean"],
      image: "🍫",
      inStock: true,
      stockQuantity: 25,
      unit: "200g",
      rating: 4.6,
      reviews: 78,
      tags: ["Pure", "Organic", "Premium"],
      supplier: "Chocolate World",
    },
    {
      name: "Protein powder",
      description: "High-quality whey protein powder for muscle building",
      price: 1200,
      originalPrice: 1500,
      category: "Supplements",
      dietCompatible: ["vegetarian"],
      image: "💪",
      inStock: true,
      stockQuantity: 20,
      unit: "1kg",
      rating: 4.8,
      reviews: 345,
      tags: ["High Quality", "Muscle Building", "Premium"],
      supplier: "Fitness Nutrition",
    },
    {
      name: "Banana",
      description: "Fresh organic bananas, perfect for smoothies and snacks",
      price: 40,
      originalPrice: 50,
      category: "Fruits",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🍌",
      inStock: true,
      stockQuantity: 120,
      unit: "1kg",
      rating: 4.5,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Beef bones",
      description: "Premium beef bones for making nutritious bone broth",
      price: 150,
      originalPrice: 180,
      category: "Meat",
      dietCompatible: ["keto", "paleo", "mediterranean"],
      image: "🦴",
      inStock: true,
      stockQuantity: 15,
      unit: "1kg",
      rating: 4.7,
      reviews: 45,
      tags: ["Premium", "Nutritious", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Carrots",
      description: "Fresh organic carrots, rich in beta-carotene",
      price: 35,
      originalPrice: 45,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥕",
      inStock: true,
      stockQuantity: 90,
      unit: "500g",
      rating: 4.6,
      reviews: 78,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Apple cider vinegar",
      description: "Raw unfiltered apple cider vinegar with mother",
      price: 120,
      originalPrice: 150,
      category: "Condiments",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍎",
      inStock: true,
      stockQuantity: 30,
      unit: "500ml",
      rating: 4.7,
      reviews: 89,
      tags: ["Raw", "Unfiltered", "Therapeutic"],
      supplier: "Health Foods Co.",
    },
  ],

  partnerships: [
    {
      name: "Fresh Valley Farms",
      type: "Organic Produce",
      location: "Pune, Maharashtra",
      savings: "15-25%",
      products: [
        "Fresh tomatoes",
        "Organic spinach",
        "Bell peppers",
        "Carrots",
      ],
      image: "🌾",
      rating: 4.8,
      delivery: "Same day",
      certification: "USDA Organic",
      contact: "+91-98765-43210",
      website: "www.freshvalleyfarms.com",
    },
    {
      name: "Mountain Dairy Co.",
      type: "Dairy Products",
      location: "Mumbai, Maharashtra",
      savings: "10-20%",
      products: ["Fresh milk", "Curd", "Paneer", "Ghee"],
      image: "🥛",
      rating: 4.7,
      delivery: "Next day",
      certification: "FSSAI Approved",
      contact: "+91-98765-43211",
      website: "www.mountaindairy.com",
    },
    {
      name: "Coastal Fish Market",
      type: "Seafood",
      location: "Mumbai, Maharashtra",
      savings: "20-30%",
      products: ["Fresh fish", "Prawns", "Crab", "Mussels"],
      image: "🐟",
      rating: 4.9,
      delivery: "Same day",
      certification: "FSSAI Approved",
      contact: "+91-98765-43212",
      website: "www.coastalfishmarket.com",
    },
  ],
};

async function seedDatabase() {
  try {
    console.log("Starting database seeding...");
    const uri = process.env.MONGODB_URI.toString();
    console.log("Connecting to:", uri);
    await mongoose.connect(uri, {
      dbName: process.env.MONGODB_DB,
    });
    console.log("✅ Connected to MongoDB");

    // Clear existing data
    console.log("🗑️ Clearing existing data...");
    await Product.deleteMany({});
    await DietPlan.deleteMany({});
    await Recipe.deleteMany({});
    await Partnership.deleteMany({});
    console.log("✅ Cleared existing data");

    // Seed data
    console.log("📊 Inserting seed data...");

    console.log("🛒 Inserting products...");
    const products = await Product.insertMany(seedData.products);

    console.log("🥗 Inserting diet plans...");
    const dietPlans = await DietPlan.insertMany(seedData.dietPlans);

    console.log("🍳 Inserting recipes...");
    const recipes = await Recipe.insertMany(seedData.recipes);

    console.log("🤝 Inserting partnerships...");
    const partnerships = await Partnership.insertMany(seedData.partnerships);

    console.log("✅ Database seeded successfully!");
    console.log(`🛒 Products: ${products.length}`);
    console.log(`🥗 Diet Plans: ${dietPlans.length}`);
    console.log(`🍳 Recipes: ${recipes.length}`);
    console.log(`🤝 Partnerships: ${partnerships.length}`);

    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
}

seedDatabase();
