import mongoose from "mongoose";
import dotenv from "dotenv";
import User from "./models/User.js";
import Product from "./models/Product.js";
import DietPlan from "./models/DietPlan.js";
import Recipe from "./models/Recipe.js";
import Partnership from "./models/Partnership.js";
import UserProgress from "./models/UserProgress.js";

dotenv.config();

const seedData = {
  users: [
    {
      firstName: "Demo",
      lastName: "User",
      email: "demo@nutricart.com",
      password: "demo123",
      profileComplete: true,
      createdAt: "2024-01-15T10:00:00Z",
      lastLogin: "2024-01-20T15:30:00Z",
      subscription: "premium",
      preferences: {
        dietaryRestrictions: ["Lactose Intolerant"],
        allergies: ["Peanuts"],
        budget: 8000,
        healthGoals: ["Weight Loss", "Muscle Gain"],
        preferredDiets: ["Keto", "Mediterranean"],
      },
    },
    {
      firstName: "Sarah",
      lastName: "Johnson",
      email: "sarah@example.com",
      password: "password123",
      profileComplete: true,
      createdAt: "2024-01-10T09:00:00Z",
      lastLogin: "2024-01-19T14:20:00Z",
      subscription: "free",
      preferences: {
        dietaryRestrictions: ["Vegetarian"],
        allergies: [],
        budget: 5000,
        healthGoals: ["Heart Health"],
        preferredDiets: ["Mediterranean", "DASH"],
      },
    },
  ],

  recipes: [
    {
      name: "Quinoa Buddha Bowl",
      description:
        "A delicious and nutritious meal perfect for your diet plan.",
      difficulty: "Easy",
      cookingTime: "25 minutes",
      servings: 2,
      calories: 420,
      image: "🥗",
      tags: ["Vegan", "High Protein", "Budget Friendly"],
      ingredients: [
        {
          name: "Quinoa",
          productName: "Quinoa",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Sweet potato",
          productName: "Sweet potato",
          quantity: "1 medium",
          inPantry: false,
        },
        {
          name: "Chickpeas",
          productName: "Chickpeas",
          quantity: "1 cup",
          inPantry: false,
        },
        {
          name: "Kale",
          productName: "Kale",
          quantity: "2 cups",
          inPantry: false,
        },
        {
          name: "Avocado",
          productName: "Avocado",
          quantity: "1",
          inPantry: false,
        },
      ],
      instructions: [
        "Cook quinoa according to package instructions",
        "Roast sweet potato until tender",
        "Drain and rinse chickpeas",
        "Massage kale with olive oil",
        "Arrange all ingredients in a bowl and enjoy!",
      ],
      nutrition: {
        calories: 420,
        protein: "15g",
        fat: "18g",
        carbs: "45g",
        fiber: "12g",
      },
      dietCompatible: ["vegan", "vegetarian", "gluten-free"],
      author: "Chef Sarah",
      rating: 4.8,
      reviews: 127,
    },
    {
      name: "Mediterranean Salmon",
      description:
        "A delicious and nutritious meal perfect for your diet plan.",
      difficulty: "Medium",
      cookingTime: "35 minutes",
      servings: 2,
      calories: 580,
      image: "🐟",
      tags: ["High Protein", "Omega-3", "Premium"],
      ingredients: [
        {
          name: "Salmon fillet",
          productName: "Salmon fillet",
          quantity: "2 pieces",
          inPantry: false,
        },
        {
          name: "Olive oil",
          productName: "Olive oil",
          quantity: "2 tbsp",
          inPantry: false,
        },
        {
          name: "Lemon",
          productName: "Lemon",
          quantity: "1",
          inPantry: false,
        },
        {
          name: "Fresh herbs",
          productName: "Fresh herbs",
          quantity: "1/4 cup",
          inPantry: false,
        },
        {
          name: "Quinoa",
          productName: "Quinoa",
          quantity: "1 cup",
          inPantry: false,
        },
      ],
      instructions: [
        "Season salmon with herbs and lemon",
        "Heat olive oil in a pan",
        "Cook salmon until flaky",
        "Cook quinoa as a side",
        "Serve with fresh herbs and lemon wedges",
      ],
      nutrition: {
        calories: 580,
        protein: "45g",
        fat: "32g",
        carbs: "28g",
        fiber: "4g",
      },
      dietCompatible: ["keto", "paleo", "mediterranean"],
      author: "Chef Maria",
      rating: 4.6,
      reviews: 89,
    },
  ],

  dietPlans: [
    {
      name: "Keto",
      description: "High-fat, low-carb diet for weight loss and energy",
      benefits: [
        "Rapid weight loss",
        "Increased energy",
        "Mental clarity",
        "Stable blood sugar",
      ],
      difficulty: "Medium",
      duration: "2-4 weeks",
      color: "from-purple-500 to-pink-500",
      icon: "🥑",
      price: 0,
      features: [
        "Meal plans",
        "Grocery lists",
        "Progress tracking",
        "Community support",
      ],
      sampleMeals: ["Avocado & Eggs", "Salmon with Greens", "Keto Smoothie"],
      restrictions: ["Low carb", "High fat", "Moderate protein"],
      suitableFor: ["Weight loss", "Diabetes management", "Energy boost"],
      weeklyMeals: [],
      groceryList: [
        "Avocados",
        "Salmon",
        "Chicken breast",
        "Eggs",
        "Coconut oil",
        "Almonds",
      ],
      nutritionInfo: {
        calories: 1800,
        protein: 120,
        carbs: 20,
        fat: 140,
        fiber: 25,
      },
    },
    {
      name: "Mediterranean",
      description: "Heart-healthy diet inspired by Mediterranean cuisine",
      benefits: [
        "Heart health",
        "Longevity",
        "Brain function",
        "Reduced inflammation",
      ],
      difficulty: "Easy",
      duration: "Lifestyle",
      color: "from-blue-500 to-cyan-500",
      icon: "🫒",
      price: 0,
      features: [
        "Balanced nutrition",
        "Fresh ingredients",
        "Flexible meal planning",
        "Family-friendly",
      ],
      sampleMeals: ["Greek Salad", "Grilled Fish", "Hummus & Pita"],
      restrictions: [
        "Moderate portions",
        "Limited red meat",
        "Low processed foods",
      ],
      suitableFor: ["Heart health", "Weight maintenance", "General wellness"],
      weeklyMeals: [],
      groceryList: [
        "Olive oil",
        "Fish and seafood",
        "Fresh vegetables",
        "Whole grains",
        "Nuts and seeds",
        "Herbs and spices",
      ],
      nutritionInfo: {
        calories: 2000,
        protein: 100,
        carbs: 200,
        fat: 70,
        fiber: 30,
      },
    },
    {
      name: "Vegan",
      description: "Plant-based nutrition for ethical and health benefits",
      benefits: [
        "Lower cholesterol",
        "Reduced cancer risk",
        "Environmental impact",
        "Ethical choice",
      ],
      difficulty: "Medium",
      duration: "Lifestyle",
      color: "from-green-500 to-emerald-500",
      icon: "🌱",
      price: 0,
      features: [
        "Plant-based recipes",
        "Nutrition guidance",
        "Meal prep tips",
        "Community support",
      ],
      sampleMeals: ["Tofu Scramble", "Lentil Curry", "Vegan Buddha Bowl"],
      restrictions: ["No animal products", "No dairy", "No eggs"],
      suitableFor: [
        "Ethical eating",
        "Health improvement",
        "Environmental consciousness",
      ],
      weeklyMeals: [],
      groceryList: [
        "Tofu and tempeh",
        "Legumes",
        "Fresh vegetables",
        "Whole grains",
        "Nuts and seeds",
        "Plant milk",
      ],
      nutritionInfo: {
        calories: 1800,
        protein: 80,
        carbs: 250,
        fat: 60,
        fiber: 35,
      },
    },
  ],

  products: [
    {
      name: "Quinoa",
      description: "Premium organic quinoa rich in protein and fiber",
      price: 120,
      originalPrice: 150,
      category: "Grains",
      dietCompatible: ["vegan", "vegetarian", "gluten-free", "keto", "paleo"],
      image: "🌾",
      inStock: true,
      stockQuantity: 50,
      unit: "1kg",
      rating: 4.8,
      reviews: 124,
      supplier: "Fresh Valley Farms",
      tags: ["Organic", "Premium", "Local"],
    },
    {
      name: "Sweet potato",
      description: "Fresh organic sweet potatoes, rich in vitamins and fiber",
      price: 40,
      originalPrice: 50,
      category: "Vegetables",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🍠",
      inStock: true,
      stockQuantity: 100,
      unit: "500g",
      rating: 4.7,
      reviews: 156,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Chickpeas",
      description: "Organic chickpeas, excellent source of plant protein",
      price: 60,
      originalPrice: 75,
      category: "Legumes",
      dietCompatible: ["vegan", "vegetarian", "mediterranean", "dash"],
      image: "🫘",
      inStock: true,
      stockQuantity: 80,
      unit: "400g can",
      rating: 4.6,
      reviews: 89,
      tags: ["Organic", "Canned", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Kale",
      description: "Fresh organic kale, nutrient-dense leafy green",
      price: 30,
      originalPrice: 40,
      category: "Vegetables",
      dietCompatible: ["vegan", "vegetarian", "keto", "paleo", "mediterranean"],
      image: "🥬",
      inStock: true,
      stockQuantity: 60,
      unit: "1 bunch",
      rating: 4.5,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Avocado",
      description: "Fresh organic avocados, perfect for healthy fats",
      price: 80,
      originalPrice: 100,
      category: "Fruits",
      dietCompatible: ["vegan", "vegetarian", "keto", "paleo", "mediterranean"],
      image: "🥑",
      inStock: true,
      stockQuantity: 100,
      unit: "1 piece",
      rating: 4.7,
      reviews: 156,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Salmon fillet",
      description: "Wild-caught Atlantic salmon, rich in omega-3 fatty acids",
      price: 400,
      originalPrice: 500,
      category: "Seafood",
      dietCompatible: ["keto", "paleo", "mediterranean", "dash"],
      image: "🐟",
      inStock: true,
      stockQuantity: 25,
      unit: "300g",
      rating: 4.9,
      reviews: 89,
      tags: ["Wild-caught", "Fresh", "Premium"],
      supplier: "Coastal Fish Market",
    },
    {
      name: "Olive oil",
      description: "Extra virgin olive oil, heart-healthy cooking oil",
      price: 200,
      originalPrice: 250,
      category: "Oils",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🫒",
      inStock: true,
      stockQuantity: 40,
      unit: "500ml",
      rating: 4.8,
      reviews: 234,
      tags: ["Extra Virgin", "Premium", "Imported"],
      supplier: "Mediterranean Imports",
    },
    {
      name: "Lemon",
      description: "Fresh organic lemons, perfect for cooking and beverages",
      price: 20,
      originalPrice: 25,
      category: "Fruits",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍋",
      inStock: true,
      stockQuantity: 150,
      unit: "1 piece",
      rating: 4.6,
      reviews: 89,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Fresh herbs",
      description: "Assorted fresh herbs for cooking and garnishing",
      price: 50,
      originalPrice: 60,
      category: "Herbs",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🌿",
      inStock: true,
      stockQuantity: 30,
      unit: "1 bunch",
      rating: 4.7,
      reviews: 45,
      tags: ["Fresh", "Local", "Organic"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Tomato",
      description: "Fresh organic tomatoes, perfect for salads and cooking",
      price: 25,
      originalPrice: 30,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍅",
      inStock: true,
      stockQuantity: 120,
      unit: "500g",
      rating: 4.6,
      reviews: 78,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Onion",
      description: "Fresh organic onions, essential cooking ingredient",
      price: 30,
      originalPrice: 35,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🧅",
      inStock: true,
      stockQuantity: 200,
      unit: "1kg",
      rating: 4.5,
      reviews: 56,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Garlic",
      description: "Fresh organic garlic, essential for flavoring dishes",
      price: 40,
      originalPrice: 50,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🧄",
      inStock: true,
      stockQuantity: 80,
      unit: "200g",
      rating: 4.7,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
        name: "Organic Quinoa",
      description: "Premium organic quinoa rich in protein and fiber",
      price: 299,
      originalPrice: 399,
      category: "Grains",
      dietCompatible: ["vegan", "vegetarian", "gluten-free", "keto", "paleo"],
      image: "🌾",
      inStock: true,
      stockQuantity: 50,
      unit: "500g",
      rating: 4.8,
      reviews: 124,
      supplier: "Fresh Valley Farms",
      tags: ["Organic", "Premium", "Local"],
    },
    {
      name: "Greek Yogurt",
      description: "Creamy Greek yogurt high in protein and probiotics",
      price: 149,
      originalPrice: 199,
      category: "Dairy",
      dietCompatible: ["vegetarian", "mediterranean", "dash"],
      image: "🥛",
      inStock: true,
      stockQuantity: 75,
      unit: "500g",
      rating: 4.6,
      reviews: 203,
      tags: ["Fresh", "Local", "Premium"],
      supplier: "Mountain Dairy Co.",
    },
    {
      name: "Almonds",
      description: "Premium raw almonds, excellent source of healthy fats",
      price: 399,
      originalPrice: 499,
      category: "Nuts",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥜",
      inStock: true,
      stockQuantity: 60,
      unit: "500g",
      rating: 4.8,
      reviews: 178,
      tags: ["Raw", "Premium", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Cucumber",
      description: "Fresh organic cucumbers, perfect for salads",
      price: 35,
      originalPrice: 45,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🥒",
      inStock: true,
      stockQuantity: 90,
      unit: "500g",
      rating: 4.5,
      reviews: 45,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
    {
      name: "Cherry Tomatoes",
      description: "Sweet cherry tomatoes, perfect for salads and cooking",
      price: 45,
      originalPrice: 55,
      category: "Vegetables",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🍅",
      inStock: true,
      stockQuantity: 70,
      unit: "250g",
      rating: 4.6,
      reviews: 67,
      tags: ["Organic", "Fresh", "Local"],
      supplier: "Fresh Valley Farms",
    },
      {
      name: "Salt",
      description: "Fine sea salt for cooking and seasoning",
      price: 25,
      originalPrice: 30,
      category: "Seasonings",
      dietCompatible: [
        "vegan",
        "vegetarian",
        "keto",
        "paleo",
        "mediterranean",
        "dash",
      ],
      image: "🧂",
      inStock: true,
      stockQuantity: 100,
      unit: "200g",
      rating: 4.5,
      reviews: 45,
      tags: ["Sea Salt", "Fine", "Essential"],
      supplier: "Spice Market",
    },
    {
      name: "Bread",
      description: "Fresh whole grain bread, perfect for toasting",
      price: 35,
      originalPrice: 40,
      category: "Bakery",
      dietCompatible: ["vegetarian"],
      image: "🍞",
      inStock: true,
      stockQuantity: 50,
      unit: "1 loaf",
      rating: 4.4,
      reviews: 89,
      tags: ["Fresh", "Whole Grain", "Local"],
      supplier: "Local Bakery",
    },
    {
      name: "Honey",
      description: "Pure natural honey, perfect for sweetening",
      price: 120,
      originalPrice: 150,
      category: "Sweeteners",
      dietCompatible: ["vegan", "vegetarian", "mediterranean"],
      image: "🍯",
      inStock: true,
      stockQuantity: 40,
      unit: "500g",
      rating: 4.7,
      reviews: 156,
      tags: ["Natural", "Pure", "Local"],
      supplier: "Honey Farm",
    },
  ],

  partnerships: [
    {
      name: "Fresh Valley Farms",
      type: "Organic Produce",
      location: "Pune, Maharashtra",
      savings: "15-25%",
      products: [
        "Fresh tomatoes",
        "Organic spinach",
        "Bell peppers",
        "Carrots",
      ],
      image: "🌾",
      rating: 4.8,
      delivery: "Same day",
      certification: "USDA Organic",
      contact: "+91-98765-43210",
      website: "www.freshvalleyfarms.com",
    },
    {
      name: "Mountain Dairy Co.",
      type: "Dairy Products",
      location: "Mumbai, Maharashtra",
      savings: "10-20%",
      products: ["Fresh milk", "Curd", "Paneer", "Ghee"],
      image: "🥛",
      rating: 4.7,
      delivery: "Next day",
      certification: "FSSAI Approved",
      contact: "+91-98765-43211",
      website: "www.mountaindairy.com",
    },
    {
      name: "Coastal Fish Market",
      type: "Seafood",
      location: "Mumbai, Maharashtra",
      savings: "20-30%",
      products: ["Fresh fish", "Prawns", "Crab", "Mussels"],
      image: "🐟",
      rating: 4.9,
      delivery: "Same day",
      certification: "FSSAI Approved",
      contact: "+91-98765-43212",
      website: "www.coastalfishmarket.com",
    },
  ],

  userProgress: [
    {
      userId: null, // Will be set after user creation
      dietPlanId: null, // Will be set after diet plan creation
      startDate: "2024-01-15T10:00:00Z",
      currentWeight: 75,
      targetWeight: 70,
      measurements: {
        chest: 95,
        waist: 85,
        hips: 95,
        arms: 32,
        thighs: 55,
      },
      progressPhotos: [],
      notes: "Starting keto diet for weight loss",
    },
  ],
};

async function seedDatabase() {
  try {
    const uri =
      process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/nutricart";
    await mongoose.connect(uri, {
      dbName: process.env.MONGODB_DB || "nutricart",
    });
    console.log("Connected to MongoDB");

    // Clear existing data
    await User.deleteMany({});
    await Product.deleteMany({});
    await DietPlan.deleteMany({});
    await Recipe.deleteMany({});
    await Partnership.deleteMany({});
    await UserProgress.deleteMany({});
    console.log("Cleared existing data");

    // Seed data
    const users = await User.insertMany(seedData.users);
    const products = await Product.insertMany(seedData.products);
    const dietPlans = await DietPlan.insertMany(seedData.dietPlans);
    const recipes = await Recipe.insertMany(seedData.recipes);
    const partnerships = await Partnership.insertMany(seedData.partnerships);
    const userProgress = await UserProgress.insertMany(seedData.userProgress);

    console.log("Database seeded successfully!");
    console.log(`Users: ${users.length}`);
    console.log(`Products: ${products.length}`);
    console.log(`Diet Plans: ${dietPlans.length}`);
    console.log(`Recipes: ${recipes.length}`);
    console.log(`Partnerships: ${partnerships.length}`);
    console.log(`User Progress: ${userProgress.length}`);

    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
}

seedDatabase();
